include:
  remote: 'https://github.com/git-developer/solarview-base/raw/v1.5.0/.gitlab-ci.yml'

variables:
  DOCKERFILE_URL: 'https://github.com/git-developer/solarview-base/raw/v1.5.0/Dockerfile'
  BUILD_ARGS: 'APP_NAME=smapmb-fb'
  IMAGE_TITLE: 'SolarView SMA-Proxy'
  UPDATE_CHECK_URLS: 'http://www.solarview.info/downloads/smapmb-fb.zip'
